### ISSUE TITLE
342 Error Code w/o Public Key

### ISSUE THREAD

**Issue by strukturedkaos** [simplificator/simplificator-withings#2]
Simplificator - I am using your Ruby gem. I set it up yesterday, and I was able to send requests via the simplificator-withings gem, and I received measurement data. However, when I tried the same requests today, I was receiving the 342 error code. Just to make sure that the gem wasn't at fault, I ended up using the methods in your gem to create my own request (in the format shown below), but I still received the 342 error code. 

The solution was to add the public key. It's very strange that it was working as expected yesterday and started throwing the 342 error code randomly. 

http://wbsapi.withings.net/measure?action=getmeas&
oauth_consumer_key=<Consumer Key>&
oauth_nonce=86c12b806fe26ed2d20112d50&
oauth_signature=W7nCHb3P92hyEXVzhrxrQ7b89A4=&
oauth_token=<Oauth Token>&
oauth_version=1.0&
userid=<User ID>&
publickey=<Public Key>

Is this a change that you can quickly make to the gem, or should I just make a pull request?

**Comment by pascalbetz** [comment]
Hi 

I just realized that i forgot to update the date in the gemspec so you can not get any useful information about the release dates from there. That said: i made a single change to the to_s method about 2 days ago (https://github.com/simplificator/simplificator-withings/commit/f7e3a71ffeba259d91f0aa7dd095ae55fb67095c) and then about then days ago (https://github.com/simplificator/simplificator-withings/commit/a19716c72e94c9620c2fae8b9cee4d54f97dc9dc) so i don't think that it was a change on the gem that bit you.
It happens from time to time that the withings guys break something, currently my test skript passes and i receive measurements. Can you try again?

Since the withings guys are not very responding i just can give you an educated guess: if you add the public key to params, then withings will skip OAuth and use the old authentication system. So you do not fix OAuth but bypassing it. Therefore i can not accept a pull request.

**Comment by strukturedkaos** [comment]
I tested it again, but I am still receiving the 342 error. So, I forked the repo and added the public key to the params, and it works. I'm able to pull data successfully.

I'll test OAuth again tomorrow, but in the meantime I'm able to bypass the issue with the public key.

**Comment by pascalbetz** [comment]
Hello

As mentioned: if you add public key param then you will bypass OAuth completely. If it's only a temporary solution, then this is fine. But Withings mentioned that they want to disable userid/ppublic key authentication by end of february.

What version of the gem are you using?
Are you absolutely sure that you have all the keys set correctly?

If i run this: https://gist.github.com/1778441 then i receive 342, if i add all the good keys, then code works. I use version 0.6.5 of the gem, 0.6.4 should also be alright.

**Comment by strukturedkaos** [comment]
Wow, I just discovered that I had the consumer key and secret switched. Once I fixed that stupid mistake, OAuth worked as expected, and I am able to get Withings data. Thank you for your help, Pascal!

**Comment by pascalbetz** [comment]
glad to hear.

Pascal

On Thu, Feb 9, 2012 at 8:32 PM, Don Pottinger <
reply@reply.github.com

> wrote:
> 
> Wow, I just discovered that I had the consumer key and secret switched.
> Once I fixed that stupid mistake, OAuth work as expected. Thank you for
> your help, Pascal!
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/simplificator/simplificator-withings/issues/2#issuecomment-3893916

## 

Pascal Betz
Simplificator GmbH | Pfingstweidstrasse 6 | 8005 Zürich
http://simplificator.com | tel +41 44 500 47 50 | mob +41 76 370 65 66
